### ISSUE TITLE
when i exec (python3 main.py) cause crash;BrokenPipeError: [Errno 32] Broken pipe  

### ISSUE THREAD

**Issue by Purool** [IrPgFKS0/ZXTouch-Python-Client#2]
Welcome to the CoDm ZXTouch Python Client v0.1.3 Alpha!

Press "l" to toggle input lock to window.
Press "p" to toggle printing debug information including green coordinate dots on window image.
Press "k" to change key mappings.
Press "j" to change joystick center position.
Press "esc" to reset all finger indices.
Press "0" quit.
[2022-06-19 15:28:41,967 ZXTouch CoDm Client v0.1.3/INFO] Resetting finger indices
Traceback (most recent call last):
  File "/Users/pur/Downloads/ZXTouch-Python-Client-main/main.py", line 540, in <module>
    create_aio_loop()
  File "/Users/pur/Downloads/ZXTouch-Python-Client-main/main.py", line 505, in create_aio_loop
    asyncio.run(run())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/Users/pur/Downloads/ZXTouch-Python-Client-main/main.py", line 437, in run
    await input_monitor()
  File "/Users/pur/Downloads/ZXTouch-Python-Client-main/main.py", line 299, in input_monitor
    await reset_fingers()
  File "/Users/pur/Downloads/ZXTouch-Python-Client-main/main.py", line 405, in reset_fingers
    await sender(None, f"{TOUCH_TASK}{SINGLE_EVENT}{TOUCH_UP}{'%02d' % i}", '1000', '01000')
  File "/Users/pur/Downloads/ZXTouch-Python-Client-main/main.py", line 377, in sender
    s.send(f"{data}{x}{y}\r\n".encode())
BrokenPipeError: [Errno 32] Broken pipe

**Comment by IrPgFKS0** [comment]
It looks like the connection failed between your computer (I assume Mac) and the jailbroken iDevice.  This is not a program error.

I might be able to help if you can provide some more info about the network information, what is the computer IP and iDevice ip and version of the ZXtouch client installed on the iDevice, also is ZXTouch still running on the iDevice (the jailbreak will expire after some time and close the ZXTouch server (aka Socket pipe)?

**Comment by Purool** [comment]
Thank you for your reply. With your tips,i changed my imac network same as iphone connected.it works!
